snd-soc-adi-axi-i2s-objs := axi-i2s.o
snd-soc-adi-axi-spdif-objs := axi-spdif.o
snd-soc-adv7511-hdmi-objs := adv7511_hdmi.o
snd-soc-te0720-pcm1754-objs := te0720_pcm1754.o
snd-soc-zed-adau1761-objs := zed_adau1761.o
snd-soc-zybo-pcm1794a-objs := zybo_pcm1794a.o
snd-soc-zybo-at1201-objs := zybo_at1201.o

obj-$(CONFIG_SND_SOC_ADI_AXI_I2S) += snd-soc-adi-axi-i2s.o
obj-$(CONFIG_SND_SOC_ADI_AXI_SPDIF) += snd-soc-adi-axi-spdif.o

obj-$(CONFIG_SND_SOC_ADV7511_HDMI) += snd-soc-adv7511-hdmi.o
obj-$(CONFIG_SND_SOC_ZED_ADAU1761) += snd-soc-zed-adau1761.o
obj-$(CONFIG_SND_TE0720_SOC_PCM1754) += snd-soc-te0720-pcm1754.o
obj-$(CONFIG_SND_ZYBO_SOC_PCM1794A) += snd-soc-zybo-pcm1794a.o
obj-$(CONFIG_SND_ZYBO_SOC_AT1201) += snd-soc-zybo-at1201.o
